# Generated by Django 5.1.6 on 2025-05-15 14:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalesstock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlysalesstock',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlysalesstock',
            name='sales_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlysalesstock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monthlysalesstock',
            name='month',
            field=models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], max_length=10),
        ),
        migrations.AlterField(
            model_name='monthlysalesstock',
            name='sales',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlysalesstock',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='monthlysalesstock',
            index=models.Index(fields=['organization', 'year'], name='API_monthly_organiz_f5be90_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlysalesstock',
            index=models.Index(fields=['year', 'month'], name='API_monthly_year_8e9a8d_idx'),
        ),
    ]
