# Generated by Django 5.1.6 on 2025-04-17 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Use the first day of the month for consistency, e.g., 2025-04-01')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_values', to='API.investment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_investments', to='API.organization')),
            ],
            options={
                'ordering': ['month'],
                'unique_together': {('investment', 'month')},
            },
        ),
    ]
