# Generated by Django 5.1.6 on 2025-05-15 14:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_monthlysalesstock_created_at_monthlysalesstock_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='quantity_sold',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.BigIntegerField(),
        ),
    ]
