# Generated by Django 5.1.6 on 2025-05-15 HH:MM

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_stock_quantity_sold_alter_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockhistory',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
